### ISSUE TITLE
`No wrap` to links 

### ISSUE THREAD

**Issue by tusharnankani** [ChoukseyKhushbu/Gitzilla#15]
There is no wrapping for links, it goes outside the container and spoils the UI!
Apart from that, the website is very ***neat and clean***. Absolutely **loved it**!

![Screenshot (104)](https://user-images.githubusercontent.com/61280281/88598831-d28f7200-d087-11ea-9cc0-28ff5b9126fb.png)

Also, try adding a favicon to your project: *a cherry on the cake!*

**Comment by ChoukseyKhushbu** [comment]
Thank you very much @tusharnankani for pointing out this bug. 😦 I will fix it very soon. 
And yes adding a favicon is a great idea. Surely gonna do it and close this issue. 
Thanks.😁

**Comment by KartikSoneji** [comment]
Adding `overflow-wrap: break-word;` or `overflow-wrap: anywhere;` here should fix the issue.

https://github.com/ChoukseyKhushbu/Gitzilla/blob/c47f765447e03f53fca097a076c938df0dd091fa/src/index.scss#L210-L213

**Comment by ChoukseyKhushbu** [comment]
> Adding `overflow-wrap: break-word;` or `overflow-wrap: anywhere;` here should fix the issue.
> 
> https://github.com/ChoukseyKhushbu/Gitzilla/blob/c47f765447e03f53fca097a076c938df0dd091fa/src/index.scss#L210-L213

Yup! You are right! @KartikSoneji. You could also have created a PR if you have figured out the solution. I would be happy to merge it.
But no issues, I have fixed it by myself :sweat_smile: 

Also @tusharnankani it would be great if you have also provided the tests (username/profiles) which would reproduce this bug. It would have been easier to test. :hugs:

**Comment by tusharnankani** [comment]
Yes, I should have mentioned it, @ChoukseyKhushbu My bad! 

It was infact @KartikSoneji's username. XD
