### ISSUE TITLE
Gitzilla Redirecting Github pages to Netlify

### ISSUE THREAD

**Issue by garvit-joshi** [ChoukseyKhushbu/Gitzilla#30]
I have a GitHub page as (https://garvit-joshi.github.io/HackerRank/) in my [Profile](https://gitzilla.netlify.app/users/garvit-joshi) when I click on that link in Gitzilla, it Redirects me to ```https://gitzilla.netlify.app/users/garvit-joshi.github.io/HackerRank/``` which is not valid and throws a 404 error.
![Screenshot from 2020-08-02 02-35-22](https://user-images.githubusercontent.com/55401175/89110561-7c487780-d469-11ea-91c6-65823f07eb7e.png)

**Comment by ChoukseyKhushbu** [comment]
Oh, I see. Maybe you have not appended `https://` to your URL. That's why this problem is occurring. If you edit the URL in your GitHub profile settings. It will work.
Though thanks for pointing out this edge case. I will fix the code to append https in the URLs if it's not present.
