### ISSUE TITLE
Add a screenshot of the project to the README

### ISSUE THREAD

**Issue by BOLT04** [ChoukseyKhushbu/Gitzilla#43]
Hi everyone 👋,

**Description**:
This project's `README` looks great, but what does everyone think about adding a screenshot of the app, to showcase it before anyone clicks on the link to visit the live app?

Something like this:
![imagem](https://user-images.githubusercontent.com/18630253/99722270-568ebf00-2aa8-11eb-9958-6c5016de20d8.png)

Or the result of someone's resume after inputting their profile. 

**Objective**:
This way a new contributor or user looking at the project, gets a glimpse of what your project does, and how it looks 😃

PS: This was an idea from Eddie on [this YouTube video](https://youtu.be/N34ViIk0C0k?t=180) 😄

**Comment by ChoukseyKhushbu** [comment]
Hey @BOLT04,
Thank you so much for creating this issue. 
I will tag it as `good first issue`. It will be easy for beginners to implement.

**Comment by bloodzmoon** [comment]
Hi! I want to fix this issue. I'm very new to this world. Please let me do this I'll try my best 😀

**Comment by bloodzmoon** [comment]
I've resolved it. Please review my pull request #44
